# Numpy的使用
## 在Tensorflow中我們會大量使用到numpy的陣列，請依照以下提示找出陣列的各種資訊

In [1]:
import numpy as np

## 1.請建立並印出1個3x4，元素都是0的ndarray A與1個3x4，元素都是1的ndarray B

In [11]:
 A = np.zeros([3,4]); A


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
 B = np.ones([3,4]); B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 2.請將以上2個陣列相加成另一個ndarray C並印出

In [13]:
C = A + B; C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
C = np.add(A,B); C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 3.將C乘以2倍後取該陣列的transpose存成陣列D並印出

In [15]:
D = (C * 2).T
D

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## 4.將B與D做矩陣相乘存成陣列E並印出

In [24]:
E= B.dot(D); E

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])